import React from "react";
import "./buttons.css";

class Buttons extends React.Component {
  render() {
    return (
      <div id="pad">
        <div id="display">{this.props.display}</div>
        <button id="clear" onClick={this.props.onClear}>
          AC
        </button>
        <button
          value="/"
          id="divide"
          onClick={this.props.onOperator}
          className="operation"
        >
          /
        </button>
        <button
          value="*"
          id="multiply"
          className="operation"
          onClick={this.props.onOperator}
        >
          *
        </button>
        <button
          value={7}
          id="seven"
          onClick={this.props.onClick}
          className="number"
        >
          7
        </button>
        <button
          id="eight"
          value={8}
          className="number"
          onClick={this.props.onClick}
        >
          8
        </button>
        <button
          id="nine"
          value={9}
          className="number"
          onClick={this.props.onClick}
        >
          9
        </button>
        <button
          value="-"
          id="subtract"
          className="operation"
          onClick={this.props.onOperator}
        >
          -
        </button>
        <button
          id="four"
          value={4}
          className="number"
          onClick={this.props.onClick}
        >
          4
        </button>
        <button
          id="five"
          value={5}
          className="number"
          onClick={this.props.onClick}
        >
          5
        </button>
        <button
          id="six"
          value={6}
          className="number"
          onClick={this.props.onClick}
        >
          6
        </button>
        <button
          value="+"
          id="add"
          className="operation"
          onClick={this.props.onOperator}
        >
          +
        </button>
        <button
          id="one"
          value={1}
          className="number"
          onClick={this.props.onClick}
        >
          1
        </button>
        <button
          id="two"
          value={2}
          className="number"
          onClick={this.props.onClick}
        >
          2
        </button>
        <button
          id="three"
          value={3}
          className="number"
          onClick={this.props.onClick}
        >
          3
        </button>
        <button id="equals" className="number" onClick={this.props.onEqual}>
          =
        </button>
        <button
          id="zero"
          value={0}
          className="number"
          onClick={this.props.onClick}
        >
          0
        </button>
        <button
          value="."
          id="decimal"
          className="number"
          onClick={this.props.onDot}
        >
          .
        </button>
      </div>
    );
  }
}
export default Buttons;
